AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Marvel Characters SAM Template

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Parameters:
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  ImageRepo:
    Type: String
  MongoDBURI:
    Type: String
  BuildID:
    Type: String

Resources:
  MarvelCharactersNextApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Marvel-Characters-API
      Description: Gateway for Marvel Characters Site
      StageName: main
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - '*'
      Domain:
        DomainName: marvel.mikebarberry.com
        CertificateArn:
          Ref: CertificateArn
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId:
            Ref: HostedZoneId

  MarvelCharactersNextFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      FunctionName: MarvelCharacters
      Environment:
        Variables:
          NODE_ENV: production
          MONGODB_URI:
            Ref: MongoDBURI
      PackageType: Image
      ImageUri:
        Fn::Sub: ${ImageRepo}:${BuildID}
      Architectures:
        - x86_64
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId:
              Ref: MarvelCharactersNextApi
            Path: /
            Method: ANY
        ProxyPlus:
          Type: Api
          Properties:
            RestApiId:
              Ref: MarvelCharactersNextApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  MarvelCharactersNextApi:
    Description: 'API Gateway endpoint URL'
    Value: 'https://marvel.mikebarberry.com'
